---

- name: system update
  action: apt update_cache=true 
 
- name: Install Docker-Engine
  apt: 
    name: "{{ packages }}"
    state: present 
    update_cache: true
  vars:
   packages :
     - docker.io
     - python-pip
     - docker-compose
#  notify:
#    - start docker
- name: add ubuntu user to docker group
  user:
   name: ubuntu
   groups: 
     - docker
     - sudo
   state: present

   
